{{- if and .Values.profiling.enabled .Values.profiling.storage.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "preloop_ai.fullname" . }}-profiling
  labels:
    {{- include "preloop_ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.profiling.storage.pvc.size }}
  {{- if .Values.profiling.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.profiling.storage.pvc.storageClassName }}
  {{- end }}
{{- end }}
