image: alpine:3.15

variables:
  CI_REGISTRY_IMAGE: $CI_REGISTRY/spacecode/spacebridge
  GIT_SUBMODULE_STRATEGY: "recursive"
  GITLAB_TOKEN: $GITLAB_TOKEN


cache:
  paths:
    - .pip-cache/

stages:
  - build
  - deploy
  - test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --destination $CI_REGISTRY_IMAGE:latest
      --registry-mirror registry.spacecode.ai
      --registry-mirror $CI_REGISTRY
      --build-arg GITLAB_TOKEN=$GITLAB_TOKEN

pre-commit:
  stage: test
  needs: []
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y git
    - pip install -U pip pre-commit ruff
  script:
    - pre-commit install
    - ruff check
    - pre-commit run --all-files

pytest:
  stage: test
  needs: []
  image: python:3.11-slim
  services:
    - postgres:13
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    DATABASE_URL: postgresql://test_user:test_password@postgres:5432/test_db
  before_script:
    - pip install -U pip
    - pip install pytest pytest-cov loguru
    - pip install --no-cache-dir -e ./SpaceModels && pip install --no-cache-dir -e ./spacesync
    - pip install -e ".[dev]"

  script:
    - export ANTHROPIC_API_KEY="mock_openai_key"
    - pytest -v

deploy:
  stage: deploy
  image: alpine/helm:3.13.2
  when: manual
  # only:
  #   - main
  #   # only for references that match a version string (v1.2.3)
  #   - /^v\d+\.\d+\.\d+$/
  environment:
    name: production
  script:
    - helm upgrade --install spacebridge ./helm/spacebridge
      --namespace spacebridge
      --set image.tag=${CI_COMMIT_SHA}
      --set config.openai.apiKey=${OPENAI_API_KEY}
      --set config.gitlab.apiKey=${GITLAB_API_KEY}
      --set config.gitlab.apiUrl=${GITLAB_API_URL}
      --set config.jira.apiKey=${JIRA_API_KEY}
      --set config.jira.apiUrl=${JIRA_API_URL}
      --set config.github.apiKey=${GITHUB_API_KEY}
      --set config.github.apiUrl=${GITHUB_API_URL}
      --set config.anthropic.apiKey=${ANTHROPIC_API_KEY}
      --set ingress.enabled=true
      --set ingress.hosts[0].name=spacebridge.io
      --set ingress.tls[0].secretName=spacebridge-tls
