apiVersion: v1
kind: Service
metadata:
  name: {{ include "preloop.fullname" . }}-gateway
  labels:
    {{- include "preloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "preloop.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
