apiVersion: v1
kind: Service
metadata:
  name: {{ include "preloop.fullname" . }}-spacelit
  labels:
    {{- include "preloop.labels" . | nindent 4 }}
    app.kubernetes.io/component: spacelit
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "preloop.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: spacelit
