"""add_issue_duplicate_table

Revision ID: 0391d4c0e7e1
Revises: 18406d4f0aaa
Create Date: 2025-06-16 12:15:51.499286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0391d4c0e7e1"
down_revision: Union[str, None] = "18406d4f0aaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_duplicate",
        sa.Column("issue1_id", sa.String(), nullable=False),
        sa.Column("issue2_id", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column(
            "decision_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("llm_provider_id", sa.String(), nullable=False),
        sa.Column("llm_model_name", sa.String(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue1_id"],
            ["issue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issue2_id"],
            ["issue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_provider_id"],
            ["llm_provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issue_duplicate_id"), "issue_duplicate", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_duplicate_id"), table_name="issue_duplicate")
    op.drop_table("issue_duplicate")
    # ### end Alembic commands ###
