"""add_llm_model_and_duplicate_table

Revision ID: 0960346a65e0
Revises: 54dea8a96182
Create Date: 2025-06-17 17:15:45.661899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0960346a65e0"
down_revision: Union[str, None] = "54dea8a96182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_model",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("provider_name", sa.String(length=255), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=255), nullable=True),
        sa.Column("api_url", sa.String(length=255), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_model_id"), "llm_model", ["id"], unique=False)
    op.create_table(
        "issue_duplicate",
        sa.Column("issue1_id", sa.String(), nullable=False),
        sa.Column("issue2_id", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column(
            "decision_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("llm_model_id", sa.String(), nullable=False),
        sa.Column("llm_model_name", sa.String(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["issue1_id"],
            ["issue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issue2_id"],
            ["issue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_model_id"],
            ["llm_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issue_duplicate_id"), "issue_duplicate", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_duplicate_id"), table_name="issue_duplicate")
    op.drop_table("issue_duplicate")
    op.drop_index(op.f("ix_llm_model_id"), table_name="llm_model")
    op.drop_table("llm_model")
    # ### end Alembic commands ###
