"""Add tool_configuration and approval_policy tables for Phase 1B

Revision ID: 0be6b535384a
Revises: 7a8b9c0d1e2f
Create Date: 2025-10-13 14:07:55.207454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0be6b535384a"
down_revision: Union[str, None] = "7a8b9c0d1e2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "approval_policy",
        "approval_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Generic configuration for approval mechanism",
        existing_nullable=True,
    )
    op.drop_constraint(
        "approval_policy_tool_configuration_id_key", "approval_policy", type_="unique"
    )
    op.drop_index(
        "ix_approval_policy_tool_configuration_id", table_name="approval_policy"
    )
    op.create_index(
        op.f("ix_approval_policy_tool_configuration_id"),
        "approval_policy",
        ["tool_configuration_id"],
        unique=True,
    )
    op.alter_column(
        "tool_configuration",
        "tool_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="JSON schema for tool parameters",
        existing_nullable=True,
    )
    op.alter_column(
        "tool_configuration",
        "custom_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Additional configuration options",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tool_configuration",
        "custom_config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Additional configuration options",
        existing_nullable=True,
    )
    op.alter_column(
        "tool_configuration",
        "tool_schema",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="JSON schema for tool parameters",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_approval_policy_tool_configuration_id"), table_name="approval_policy"
    )
    op.create_index(
        "ix_approval_policy_tool_configuration_id",
        "approval_policy",
        ["tool_configuration_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "approval_policy_tool_configuration_id_key",
        "approval_policy",
        ["tool_configuration_id"],
    )
    op.alter_column(
        "approval_policy",
        "approval_config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Generic configuration for approval mechanism",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
