"""add_llm_provider_table

Revision ID: 18406d4f0aaa
Revises: 54dea8a96182
Create Date: 2025-06-15 09:40:29.955484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18406d4f0aaa"
down_revision: Union[str, None] = "54dea8a96182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_provider",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("provider_name", sa.String(length=255), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_provider_id"), "llm_provider", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_provider_id"), table_name="llm_provider")
    op.drop_table("llm_provider")
    # ### end Alembic commands ###
