"""Refactor tracker scoping

Revision ID: 20250617145000
Revises: 20250612135000
Create Date: 2025-06-17 14:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import logging
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "20250617145000"
down_revision = "20250612135000"
branch_labels = None
depends_on = None
logger = logging.getLogger(__name__)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracker_scope_rule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tracker_id", sa.String(length=36), nullable=False),
        sa.Column(
            "scope_type",
            sa.String(length=50),
            nullable=False,
            comment="Possible values: ORGANIZATION, PROJECT",
        ),
        sa.Column(
            "rule_type",
            sa.String(length=50),
            nullable=False,
            comment="Possible values: INCLUDE, EXCLUDE",
        ),
        sa.Column(
            "identifier",
            sa.String(length=255),
            nullable=False,
            comment="e.g., 'my-org' or 'my-org/my-repo'",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tracker_id"], ["tracker.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns("tracker")
    if any(c["name"] == "included_project_identifiers" for c in columns):
        op.drop_column("tracker", "included_project_identifiers")
    if any(c["name"] == "excluded_project_identifiers" for c in columns):
        op.drop_column("tracker", "excluded_project_identifiers")
    if any(c["name"] == "include_future_projects" for c in columns):
        op.drop_column("tracker", "include_future_projects")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracker",
        sa.Column(
            "include_future_projects",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            server_default=sa.text("true"),
        ),
    )
    op.add_column(
        "tracker",
        sa.Column(
            "excluded_project_identifiers",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tracker",
        sa.Column(
            "included_project_identifiers",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )

    # Note: Data migration on downgrade is best-effort and may not perfectly restore state.
    # It's complex to convert rules back to the old format perfectly.
    # This will restore the structure, but data might be lost.

    op.drop_table("tracker_scope_rule")
    # ### end Alembic commands ###
