"""Refactor tracker scoping

Revision ID: 20250617145000
Revises: b2102d58db12
Create Date: 2025-06-17 14:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20250617145000"
down_revision = "b2102d58db12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tracker_scope_rule_table = op.create_table(
        "tracker_scope_rule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tracker_id", sa.String(length=36), nullable=False),
        sa.Column(
            "scope_type",
            sa.String(length=50),
            nullable=False,
            comment="Possible values: ORGANIZATION, PROJECT",
        ),
        sa.Column(
            "rule_type",
            sa.String(length=50),
            nullable=False,
            comment="Possible values: INCLUDE, EXCLUDE",
        ),
        sa.Column(
            "identifier",
            sa.String(length=255),
            nullable=False,
            comment="e.g., 'my-org' or 'my-org/my-repo'",
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tracker_id"], ["tracker.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Data migration
    conn = op.get_bind()
    res = conn.execute(
        sa.text(
            "SELECT id, included_project_identifiers, excluded_project_identifiers, include_future_projects FROM tracker"
        )
    )
    results = res.fetchall()

    for r_id, included, excluded, include_future in results:
        if include_future or not included:
            # Default is include all, so we only care about exclusions
            if excluded:
                for identifier in excluded:
                    op.execute(
                        tracker_scope_rule_table.insert().values(
                            id=sa.text("uuid_generate_v4()"),
                            tracker_id=r_id,
                            scope_type="PROJECT",
                            rule_type="EXCLUDE",
                            identifier=identifier,
                        )
                    )
        else:
            # Only specific projects are included
            if included:
                for identifier in included:
                    op.execute(
                        tracker_scope_rule_table.insert().values(
                            id=sa.text("uuid_generate_v4()"),
                            tracker_id=r_id,
                            scope_type="PROJECT",
                            rule_type="INCLUDE",
                            identifier=identifier,
                        )
                    )
            if excluded:
                for identifier in excluded:
                    op.execute(
                        tracker_scope_rule_table.insert().values(
                            id=sa.text("uuid_generate_v4()"),
                            tracker_id=r_id,
                            scope_type="PROJECT",
                            rule_type="EXCLUDE",
                            identifier=identifier,
                        )
                    )

    op.drop_column("tracker", "included_project_identifiers")
    op.drop_column("tracker", "excluded_project_identifiers")
    op.drop_column("tracker", "include_future_projects")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracker",
        sa.Column(
            "include_future_projects",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            server_default=sa.text("true"),
        ),
    )
    op.add_column(
        "tracker",
        sa.Column(
            "excluded_project_identifiers",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tracker",
        sa.Column(
            "included_project_identifiers",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )

    # Note: Data migration on downgrade is best-effort and may not perfectly restore state.
    # It's complex to convert rules back to the old format perfectly.
    # This will restore the structure, but data might be lost.

    op.drop_table("tracker_scope_rule")
    # ### end Alembic commands ###
