"""comment-refactor

Revision ID: 4bbe86aa820f
Revises: b31b0996ab89
Create Date: 2025-07-21 20:42:10.351043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bbe86aa820f"
down_revision: Union[str, None] = "b31b0996ab89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("author", sa.String(length=255), nullable=True))
    op.add_column(
        "comment", sa.Column("tracker_id", sa.String(length=36), nullable=True)
    )
    op.execute(
        """
        UPDATE comment
        SET tracker_id = issue.tracker_id
        FROM issue
        WHERE comment.issue_id = issue.id;
        """
    )
    op.alter_column("comment", "tracker_id", nullable=False)
    op.drop_index("ix_comment_author_id", table_name="comment")
    op.create_index(op.f("ix_comment_author"), "comment", ["author"], unique=False)
    op.create_index(
        op.f("ix_comment_tracker_id"), "comment", ["tracker_id"], unique=False
    )
    op.drop_constraint("comment_author_id_fkey", "comment", type_="foreignkey")
    op.create_foreign_key(
        "fk_comment_tracker_id",
        "comment",
        "tracker",
        ["tracker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("comment", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment",
        sa.Column(
            "author_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.create_foreign_key(
        "comment_author_id_fkey",
        "comment",
        "account",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_comment_tracker_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_author"), table_name="comment")
    op.create_index("ix_comment_author_id", "comment", ["author_id"], unique=False)
    op.drop_column("comment", "tracker_id")
    op.drop_column("comment", "author")
    # ### end Alembic commands ###
