"""add_webhook_last_verified_at_to_project

Revision ID: 4e94694b4381
Revises: c07e5024f8df
Create Date: 2025-05-29 00:14:19.265601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e94694b4381"
down_revision: Union[str, None] = "c07e5024f8df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "webhook_last_verified_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "webhook_last_verified_at")
    # ### end Alembic commands ###
