"""create_comment_table

Revision ID: 54dea8a96182
Revises: a5bd730968f3
Create Date: 2025-05-27 17:15:27.486781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54dea8a96182"
down_revision: Union[str, None] = "a5bd730968f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.String(length=50),
            nullable=False,
            comment="Type of comment (e.g., 'issue', 'merge_request')",
        ),
        sa.Column("issue_id", sa.String(length=36), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["author_id"], ["account.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["issue_id"], ["issue.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_author_id"), "comment", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_comment_id"), "comment", ["id"], unique=False)
    op.create_index(op.f("ix_comment_issue_id"), "comment", ["issue_id"], unique=False)
    op.add_column(
        "issueembedding", sa.Column("comment_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_issueembedding_comment_id"),
        "issueembedding",
        ["comment_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uix_issue_embedding_model",
        "issueembedding",
        ["issue_id", "comment_id", "embedding_model_id"],
    )
    op.create_foreign_key(
        None, "issueembedding", "comment", ["comment_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issueembedding", type_="foreignkey")
    op.drop_constraint("uix_issue_embedding_model", "issueembedding", type_="unique")
    op.drop_index(op.f("ix_issueembedding_comment_id"), table_name="issueembedding")
    op.drop_column("issueembedding", "comment_id")
    op.drop_index(op.f("ix_comment_issue_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_author_id"), table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
