"""Unify LLMModel and ModelConfiguration into AIModel

Revision ID: 6b2f38e54904
Revises: 01f0de57ea4b
Create Date: 2025-08-04 15:06:52.669694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b2f38e54904"
down_revision: Union[str, None] = "01f0de57ea4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_model",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provider_name", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("api_endpoint", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "model_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_model_account_id"), "ai_model", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_model_model_identifier"),
        "ai_model",
        ["model_identifier"],
        unique=False,
    )
    op.create_index(op.f("ix_ai_model_name"), "ai_model", ["name"], unique=False)
    op.drop_constraint(
        "issue_duplicate_llm_model_id_fkey", "issue_duplicate", type_="foreignkey"
    )

    # Migrate data from llm_model to ai_model
    op.execute(
        """
        INSERT INTO ai_model (id, name, provider_name, model_identifier, api_endpoint, api_key, account_id, is_default, meta_data, created_at, updated_at)
        SELECT id::uuid, name, provider_name, model_name, api_url, api_key, account_id, is_default, meta_data, created_at, updated_at
        FROM llm_model
    """
    )
    op.execute("DROP INDEX IF EXISTS ix_llm_model_id")
    op.drop_table("llm_model")
    op.add_column(
        "flow", sa.Column("ai_model_id", sa.UUID(as_uuid=True), nullable=True)
    )
    op.add_column(
        "issue_duplicate",
        sa.Column("ai_model_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "issue_duplicate",
        sa.Column("ai_model_name", sa.String(length=255), nullable=True),
    )
    op.create_foreign_key(
        "fk_flow_ai_model_id",
        "flow",
        "ai_model",
        ["ai_model_id"],
        ["id"],
    )
    op.drop_column("flow", "model_configuration_id")
    op.drop_column("issue_duplicate", "llm_model_id")
    op.drop_column("issue_duplicate", "llm_model_name")
    op.create_foreign_key(
        "fk_issue_duplicate_ai_model_id",
        "issue_duplicate",
        "ai_model",
        ["ai_model_id"],
        ["id"],
    )
    op.drop_index(
        "idx_issueembedding_vector_128",
        table_name="issueembedding",
        postgresql_using="hnsw",
    )

    # ### end Alembic commands ###

    # ### data migration ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_issueembedding_vector_128")
    op.create_index(
        "idx_issueembedding_vector_128",
        "issueembedding",
        [sa.literal_column("(subvector(embedding, 1, 128)::vector(128))")],
        unique=False,
        postgresql_with={"m": "16", "ef_construction": "40"},
        postgresql_using="hnsw",
        postgresql_ops={
            "(subvector(embedding, 1, 128)::vector(128))": "vector_cosine_ops"
        },
    )
    inspector = sa.inspect(op.get_bind())
    issue_duplicate_columns = [
        c["name"] for c in inspector.get_columns("issue_duplicate")
    ]
    if "llm_model_id" not in issue_duplicate_columns:
        op.add_column(
            "issue_duplicate",
            sa.Column(
                "llm_model_id",
                sa.VARCHAR(length=36),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "llm_model_name" not in issue_duplicate_columns:
        op.add_column(
            "issue_duplicate",
            sa.Column(
                "llm_model_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            ),
        )
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    issue_duplicate_columns = [
        c["name"] for c in inspector.get_columns("issue_duplicate")
    ]
    if "ai_model_name" in issue_duplicate_columns:
        op.drop_column("issue_duplicate", "ai_model_name")
    if "ai_model_id" in issue_duplicate_columns:
        op.drop_column("issue_duplicate", "ai_model_id")
    inspector = sa.inspect(op.get_bind())
    foreign_keys = inspector.get_foreign_keys("issue_duplicate")
    if any(fk["name"] == "fk_issue_duplicate_ai_model_id" for fk in foreign_keys):
        op.drop_constraint(
            "fk_issue_duplicate_ai_model_id", "issue_duplicate", type_="foreignkey"
        )
    inspector = sa.inspect(op.get_bind())
    if not inspector.has_table("llm_model"):
        op.create_table(
            "llm_model",
            sa.Column(
                "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            ),
            sa.Column(
                "account_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
            ),
            sa.Column(
                "provider_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "model_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "model_version",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "api_url", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            ),
            sa.Column(
                "api_key", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            ),
            sa.Column("is_default", sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column(
                "meta_data",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
            sa.Column(
                "created_at",
                postgresql.TIMESTAMP(),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                postgresql.TIMESTAMP(),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["account_id"],
                ["account.id"],
                name="llm_model_account_id_fkey",
            ),
            sa.PrimaryKeyConstraint("id", name="llm_model_pkey"),
        )
    if inspector.has_table("llm_model"):
        op.create_index("ix_llm_model_id", "llm_model", ["id"], unique=False)
    inspector = sa.inspect(op.get_bind())
    foreign_keys = inspector.get_foreign_keys("issue_duplicate")
    if not any(
        fk["name"] == "issue_duplicate_llm_model_id_fkey" for fk in foreign_keys
    ):
        op.create_foreign_key(
            "issue_duplicate_llm_model_id_fkey",
            "issue_duplicate",
            "llm_model",
            ["llm_model_id"],
            ["id"],
        )
    inspector = sa.inspect(op.get_bind())
    flow_columns = [c["name"] for c in inspector.get_columns("flow")]
    if "model_configuration_id" not in flow_columns:
        op.add_column(
            "flow",
            sa.Column(
                "model_configuration_id",
                sa.VARCHAR(length=36),
                autoincrement=False,
                nullable=True,
            ),
        )
    inspector = sa.inspect(op.get_bind())
    foreign_keys = inspector.get_foreign_keys("flow")
    if any(fk["name"] == "fk_flow_ai_model_id" for fk in foreign_keys):
        op.drop_constraint("fk_flow_ai_model_id", "flow", type_="foreignkey")
    op.drop_column("flow", "ai_model_id")

    op.drop_index(op.f("ix_ai_model_name"), table_name="ai_model")
    op.drop_index(op.f("ix_ai_model_model_identifier"), table_name="ai_model")
    op.drop_index(op.f("ix_ai_model_account_id"), table_name="ai_model")
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("ai_model"):
        op.drop_table("ai_model")
    # ### end Alembic commands ###
