"""Add slug column to project table

Revision ID: 78081c979725
Revises: b2102d58db12
Create Date: 2025-05-01 14:12:33.290798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78081c979725"
down_revision: Union[str, None] = "b2102d58db12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("slug", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_project_slug"), "project", ["slug"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_slug"), table_name="project")
    op.drop_column("project", "slug")
    # ### end Alembic commands ###
