"""create_comment_table

Revision ID: 7cb89dbca31a
Revises: a5bd730968f3
Create Date: 2025-05-24 14:09:52.442606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb89dbca31a"
down_revision: Union[str, None] = "a5bd730968f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issueembedding", sa.Column("comment_id", sa.String(length=36), nullable=True)
    )
    op.drop_constraint("uix_issue_embedding_model", "issueembedding", type_="unique")
    op.create_unique_constraint(
        "uix_issue_embedding_model",
        "issueembedding",
        ["issue_id", "comment_id", "embedding_model_id"],
    )
    op.create_index(
        op.f("ix_issueembedding_comment_id"),
        "issueembedding",
        ["comment_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "issueembedding", "comment", ["comment_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issueembedding", type_="foreignkey")
    op.drop_index(op.f("ix_issueembedding_comment_id"), table_name="issueembedding")
    op.drop_constraint("uix_issue_embedding_model", "issueembedding", type_="unique")
    op.create_unique_constraint(
        "uix_issue_embedding_model",
        "issueembedding",
        ["issue_id", "embedding_model_id"],
    )
    op.drop_column("issueembedding", "comment_id")
    # ### end Alembic commands ###
