"""Add org and project identifiers to client_version_logs

Revision ID: 8142720340e0
Revises:
Create Date: 2025-04-14 15:19:48.416356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8142720340e0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_version_logs",
        sa.Column("organization_identifier", sa.String(), nullable=True),
    )
    op.add_column(
        "client_version_logs",
        sa.Column("project_identifier", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_client_version_logs_organization_identifier"),
        "client_version_logs",
        ["organization_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_version_logs_project_identifier"),
        "client_version_logs",
        ["project_identifier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_client_version_logs_project_identifier"),
        table_name="client_version_logs",
    )
    op.drop_index(
        op.f("ix_client_version_logs_organization_identifier"),
        table_name="client_version_logs",
    )
    op.drop_column("client_version_logs", "project_identifier")
    op.drop_column("client_version_logs", "organization_identifier")
    # ### end Alembic commands ###
