"""Autogenerated migration

Revision ID: 87a6b8fd3e65
Revises: bf6fac0a7c61
Create Date: 2025-07-11 18:39:58.338274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "87a6b8fd3e65"
down_revision: Union[str, None] = "bf6fac0a7c61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment",
        "external_id",
        existing_type=sa.VARCHAR(length=36),
        comment="External ID of the comment",
        existing_nullable=False,
    )
    op.alter_column(
        "flow",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "flow",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "issue", "external_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "organization",
        "last_webhook_update",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "last_polling_update",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index("ix_organization_identifier", table_name="organization")
    op.create_index(
        op.f("ix_organization_identifier"), "organization", ["identifier"], unique=False
    )
    op.alter_column(
        "tracker",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        comment="Flag for soft deletion",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tracker",
        "subscribed_events",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="List of specific webhook event names to subscribe to (e.g., ['push', 'issues']). Empty or None might imply default/all events based on client logic.",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.create_index(
        op.f("ix_tracker_is_deleted"), "tracker", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_tracker_scope_rule_id"), "tracker_scope_rule", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tracker_scope_rule_tracker_id"),
        "tracker_scope_rule",
        ["tracker_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tracker_scope_rule_tracker_id"), table_name="tracker_scope_rule"
    )
    op.drop_index(op.f("ix_tracker_scope_rule_id"), table_name="tracker_scope_rule")
    op.drop_index(op.f("ix_tracker_is_deleted"), table_name="tracker")
    op.alter_column(
        "tracker",
        "subscribed_events",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="List of specific webhook event names to subscribe to (e.g., ['push', 'issues']). Empty or None might imply default/all events based on client logic.",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tracker",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Flag for soft deletion",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_organization_identifier"), table_name="organization")
    op.create_index(
        "ix_organization_identifier", "organization", ["identifier"], unique=True
    )
    op.alter_column(
        "organization",
        "last_polling_update",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "last_webhook_update",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "issue", "external_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "flow",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "flow",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "comment",
        "external_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="External ID of the comment",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
