"""Add suggestion to issue compliance result

Revision ID: 98b2c8291a52
Revises: e681acc2f98f
Create Date: 2025-09-09 17:15:29.143149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98b2c8291a52"
down_revision: Union[str, None] = "e681acc2f98f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issuecomplianceresult", sa.Column("suggestion", sa.String(), nullable=False)
    )
    op.add_column(
        "issuecomplianceresult",
        sa.Column("annotated_description", sa.String(), nullable=True),
    )
    op.add_column("issue_duplicate", sa.Column("suggestion", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issue_duplicate", "suggestion")
    op.drop_column("issuecomplianceresult", "annotated_description")
    op.drop_column("issuecomplianceresult", "suggestion")
    # ### end Alembic commands ###
