"""Add key field to Issue model

Revision ID: a5bd730968f3
Revises: 78081c979725
Create Date: 2025-05-04 16:41:50.036931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5bd730968f3"
down_revision: Union[str, None] = "78081c979725"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issue", sa.Column("key", sa.String(length=512), nullable=True))
    op.create_index(op.f("ix_issue_key"), "issue", ["key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_key"), table_name="issue")
    op.drop_column("issue", "key")
    # ### end Alembic commands ###
