"""add_metadata_to_comment_model

Revision ID: aac7320bec27
Revises: 7cb89dbca31a
Create Date: 2025-05-25 20:39:10.070864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac7320bec27'
down_revision: Union[str, None] = '7cb89dbca31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'meta_data')
    # ### end Alembic commands ###
