"""Add project scope fields to Tracker model

Revision ID: b2102d58db12
Revises: b9496b9853dd
Create Date: 2025-04-28 01:29:43.982514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2102d58db12"
down_revision: Union[str, None] = "b9496b9853dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracker",
        sa.Column(
            "included_project_identifiers",
            sa.JSON(),
            nullable=True,
            comment="List of project identifiers (e.g., 'org/repo', 'PROJKEY') to include. None means include all by default.",
        ),
    )
    op.add_column(
        "tracker",
        sa.Column(
            "excluded_project_identifiers",
            sa.JSON(),
            nullable=True,
            comment="List of project identifiers to explicitly exclude. Takes precedence over inclusions.",
        ),
    )
    op.add_column(
        "tracker",
        sa.Column(
            "include_future_projects",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
            comment="Whether to automatically include newly discovered projects when included_project_identifiers is None.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracker", "include_future_projects")
    op.drop_column("tracker", "excluded_project_identifiers")
    op.drop_column("tracker", "included_project_identifiers")
    # ### end Alembic commands ###
