"""Change resolution column from Enum to String in issue_duplicate table

Revision ID: b31b0996ab89
Revises: 87a6b8fd3e65
Create Date: 2025-07-14 14:57:45.691319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b31b0996ab89"
down_revision: Union[str, None] = "87a6b8fd3e65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "issue_duplicate",
        "resolution",
        existing_type=postgresql.ENUM(
            "CLOSED",
            "MERGED",
            "DISAMBIGUATED",
            "DISMISSED",
            "NOT_A_DUPLICATE",
            name="issueduplicateresolution",
        ),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_index("ix_organization_identifier", table_name="organization")
    op.create_index(
        op.f("ix_organization_identifier"), "organization", ["identifier"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organization_identifier"), table_name="organization")
    op.create_index(
        "ix_organization_identifier", "organization", ["identifier"], unique=True
    )
    op.alter_column(
        "issue_duplicate",
        "resolution",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "CLOSED",
            "MERGED",
            "DISAMBIGUATED",
            "DISMISSED",
            "NOT_A_DUPLICATE",
            name="issueduplicateresolution",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
