"""Add is_deleted flag to Tracker model

Revision ID: b9496b9853dd
Revises: 8142720340e0
Create Date: 2025-04-15 21:31:33.082582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9496b9853dd"
down_revision: Union[str, None] = "8142720340e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracker",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
            comment="Flag for soft deletion",
        ),
    )
    op.create_index(
        op.f("ix_tracker_is_deleted"), "tracker", ["is_deleted"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracker_is_deleted"), table_name="tracker")
    op.drop_column("tracker", "is_deleted")
    # ### end Alembic commands ###
