"""Add resolution fields to issue_duplicate

Revision ID: bb63a3484a47
Revises: 20250617145000
Create Date: 2025-07-08 20:55:05.173226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb63a3484a47'
down_revision: Union[str, None] = '20250617145000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_duplicate', sa.Column('resolution', sa.Enum('CLOSED', 'MERGED', 'DISAMBIGUATED', 'DISMISSED', 'NOT_A_DUPLICATE', name='issueduplicateresolution'), nullable=True))
    op.add_column('issue_duplicate', sa.Column('resolution_at', sa.DateTime(), nullable=True))
    op.add_column('issue_duplicate', sa.Column('resolution_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_duplicate', 'resolution_reason')
    op.drop_column('issue_duplicate', 'resolution_at')
    op.drop_column('issue_duplicate', 'resolution')
    # ### end Alembic commands ###
