"""Add issue resolution

Revision ID: bf6fac0a7c61
Revises: 20250617145000
Create Date: 2025-07-11 16:13:40.863371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf6fac0a7c61"
down_revision: Union[str, None] = "20250617145000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issue_duplicate",
        sa.Column(
            "resolution",
            sa.Enum(
                "CLOSED",
                "MERGED",
                "DECONFLICTED",
                "DISMISSED",
                "NOT_A_DUPLICATE",
                name="issueduplicateresolution",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "issue_duplicate", sa.Column("resolution_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "issue_duplicate", sa.Column("resolution_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "issue_duplicate", sa.Column("resulting_issue1_id", sa.String(), nullable=True)
    )
    op.add_column(
        "issue_duplicate", sa.Column("resulting_issue2_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None, "issue_duplicate", "issue", ["resulting_issue1_id"], ["id"]
    )
    op.create_foreign_key(
        None, "issue_duplicate", "issue", ["resulting_issue2_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issue_duplicate", type_="foreignkey")
    op.drop_constraint(None, "issue_duplicate", type_="foreignkey")
    op.drop_column("issue_duplicate", "resulting_issue2_id")
    op.drop_column("issue_duplicate", "resulting_issue1_id")
    op.drop_column("issue_duplicate", "resolution_reason")
    op.drop_column("issue_duplicate", "resolution_at")
    op.drop_column("issue_duplicate", "resolution")
    # ### end Alembic commands ###
