"""Add webhook_secret to Organization model

Revision ID: c07e5024f8df
Revises: 18406d4f0aaa
Create Date: 2025-05-04 22:53:58.898437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c07e5024f8df"
down_revision: Union[str, None] = "18406d4f0aaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("webhook_secret", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "organization", sa.Column("last_webhook_update", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("last_polling_update", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "last_polling_update")
    op.drop_column("organization", "last_webhook_update")
    op.drop_column("organization", "webhook_secret")
    # ### end Alembic commands ###
