"""Add plan, subscription, and usage models linked to accounts

Revision ID: c6316689ee9c
Revises: 6b2f38e54904
Create Date: 2025-08-06 12:41:58.086768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6316689ee9c"
down_revision: Union[str, None] = "6b2f38e54904"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price_monthly", sa.Float(), nullable=True),
        sa.Column("price_annually", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stripe_product_id", sa.String(), nullable=True),
        sa.Column("account_id", sa.String(36), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("stripe_product_id"),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"]),
    )
    op.create_table(
        "subscription",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("account_id", sa.String(36), nullable=False),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.add_column(
        "account", sa.Column("stripe_customer_id", sa.String(255), nullable=True)
    )
    op.create_unique_constraint(
        "uq_account_stripe_customer_id", "account", ["stripe_customer_id"]
    )
    op.create_index(
        op.f("ix_subscription_account_id"), "subscription", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_plan_id"), "subscription", ["plan_id"], unique=False
    )
    op.create_table(
        "monthly_usage",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("billing_cycle_start", sa.Date(), nullable=False),
        sa.Column("billing_cycle_end", sa.Date(), nullable=False),
        sa.Column(
            "usage_counts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscription.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monthly_usage_subscription_id"),
        "monthly_usage",
        ["subscription_id"],
        unique=False,
    )
    op.drop_index("ix_accountorganization_id", table_name="accountorganization")
    op.drop_table("accountorganization")
    op.add_column("flow", sa.Column("account_id", sa.String(length=36), nullable=False))
    op.create_index(op.f("ix_flow_account_id"), "flow", ["account_id"], unique=False)
    op.drop_constraint("flow_organization_id_fkey", "flow", type_="foreignkey")
    op.create_foreign_key(None, "flow", "account", ["account_id"], ["id"])
    op.drop_column("flow", "organization_id")
    op.drop_column("flow", "created_by_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow",
        sa.Column(
            "created_by_user_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow",
        sa.Column(
            "organization_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("flow_account_id_fkey", "flow", type_="foreignkey")
    op.create_foreign_key(
        "flow_organization_id_fkey", "flow", "organization", ["organization_id"], ["id"]
    )
    op.drop_index(op.f("ix_flow_account_id"), table_name="flow")
    op.drop_column("flow", "account_id")
    op.create_table(
        "accountorganization",
        sa.Column(
            "account_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            "organization_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name="accountorganization_account_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name="accountorganization_organization_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "account_id", "organization_id", "id", name="accountorganization_pkey"
        ),
    )
    op.create_index(
        "ix_accountorganization_id", "accountorganization", ["id"], unique=False
    )
    op.drop_index(op.f("ix_monthly_usage_subscription_id"), table_name="monthly_usage")
    op.drop_table("monthly_usage")
    op.drop_index(op.f("ix_subscription_plan_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_account_id"), table_name="subscription")
    op.drop_table("subscription")
    op.drop_table("plan")
    # ### end Alembic commands ###
