"""create webhook table

Revision ID: dbd4003e5eef
Revises: 52502e04d6ef
Create Date: 2025-06-14 21:14:45.289313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbd4003e5eef"
down_revision: Union[str, None] = "52502e04d6ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook",
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_external_id"), "webhook", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_webhook_id"), "webhook", ["id"], unique=False)
    op.create_index(
        op.f("ix_webhook_project_id"), "webhook", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_project_id"), table_name="webhook")
    op.drop_index(op.f("ix_webhook_id"), table_name="webhook")
    op.drop_index(op.f("ix_webhook_external_id"), table_name="webhook")
    op.drop_table("webhook")
    # ### end Alembic commands ###
