"""Add parent_id to issues and create issue_relationship table

Revision ID: e681acc2f98f
Revises: f63a4134961a
Create Date: 2025-08-13 22:55:39.602280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e681acc2f98f"
down_revision: Union[str, None] = "f63a4134961a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_primary_key("issue_pkey", "issue", ["id"])
    op.create_table(
        "issue_relationship",
        sa.Column("source_issue_id", sa.String(length=36), nullable=False),
        sa.Column("target_issue_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "is_committed", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "comes_from_tracker",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["source_issue_id"], ["issue.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_issue_id"], ["issue.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_issue_id",
            "target_issue_id",
            "type",
            name="uq_issue_relationship_source_target_type",
        ),
    )
    op.create_index(
        op.f("ix_issue_relationship_id"), "issue_relationship", ["id"], unique=False
    )
    op.add_column("issue", sa.Column("parent_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_issue_parent_id"), "issue", ["parent_id"], unique=False)
    op.create_foreign_key(
        "issue_parent_id_fkey",
        "issue",
        "issue",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("issue_parent_id_fkey", "issue", type_="foreignkey")
    op.drop_index(op.f("ix_issue_parent_id"), table_name="issue")
    op.drop_column("issue", "parent_id")
    op.drop_table("issue_relationship")
    # op.drop_constraint("issue_pkey", "issue", type_="primary")
    # ### end Alembic commands ###
