"""Add icon to flow model

Revision ID: f63a4134961a
Revises: fee205f0e337
Create Date: 2025-08-14 15:16:25.768365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f63a4134961a"
down_revision: Union[str, None] = "fee205f0e337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flow", sa.Column("icon", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flow", "icon")
    # ### end Alembic commands ###
