"""Make account_id optional for flow presets

Revision ID: fee205f0e337
Revises: c6316689ee9c
Create Date: 2025-08-14 14:48:20.212469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fee205f0e337"
down_revision: Union[str, None] = "c6316689ee9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flow", "account_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.create_index(op.f("ix_plan_account_id"), "plan", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_account_id"), table_name="plan")
    op.alter_column(
        "flow", "account_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    # ### end Alembic commands ###
