"""Add client_version_logs table with correct FK type

Revision ID: ffab5a22b79b
Revises:
Create Date: 2025-04-11 18:46:36.074713

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffab5a22b79b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_version_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("client_version", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_version_logs_account_id"),
        "client_version_logs",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_version_logs_id"), "client_version_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_client_version_logs_ip_address"),
        "client_version_logs",
        ["ip_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_client_version_logs_ip_address"), table_name="client_version_logs"
    )
    op.drop_index(op.f("ix_client_version_logs_id"), table_name="client_version_logs")
    op.drop_index(
        op.f("ix_client_version_logs_account_id"), table_name="client_version_logs"
    )
    op.drop_table("client_version_logs")
    # ### end Alembic commands ###
