ingress:
  enabled: true
  hosts:
    - host: "{{ .Values.branchName }}.test.preloop.ai"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "{{ .Values.branchName }}.test.preloop.ai"
      secretName: preloop-test-tls
