"""Add notification emails to budget policies

Revision ID: 20831f105009
Revises: 38c140ad96cf
Create Date: 2026-04-03 23:21:02.279663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20831f105009"
down_revision: Union[str, None] = "38c140ad96cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "budget_policies",
        sa.Column("notification_emails", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("budget_policies", "notification_emails")
    # ### end Alembic commands ###
