import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { createElement, icons, type IconNode } from 'lucide';
import { UiElement } from './base';

const ICON_NAME_MAP: Record<string, string> = {
  'exclamation-triangle': 'triangle-alert',
  'exclamation-circle': 'circle-alert',
  'check-circle': 'circle-check',
  'x-circle': 'circle-x',
  'info-circle': 'info',
  'question-circle': 'circle-help',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'chevron-down': 'chevron-down',
  'chevron-up': 'chevron-up',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  check: 'check',
  x: 'x',
  plus: 'plus',
  minus: 'minus',
  pencil: 'pencil',
  edit: 'pencil',
  trash: 'trash-2',
  copy: 'copy',
  clipboard: 'clipboard',
  download: 'download',
  upload: 'upload',
  search: 'search',
  filter: 'filter',
  menu: 'menu',
  'three-dots': 'ellipsis',
  'three-dots-vertical': 'ellipsis-vertical',
  gear: 'settings',
  cog: 'settings',
  settings: 'settings',
  user: 'user',
  people: 'users',
  users: 'users',
  lock: 'lock',
  key: 'key',
  shield: 'shield',
  github: 'github',
  gitlab: 'gitlab',
  google: 'globe',
  globe: 'globe',
  mail: 'mail',
  envelope: 'mail',
  home: 'house',
  box: 'box',
  package: 'package',
  folder: 'folder',
  file: 'file',
  'file-text': 'file-text',
  code: 'code',
  terminal: 'terminal',
  server: 'server',
  layers: 'layers',
  bot: 'bot',
  zap: 'zap',
  star: 'star',
  tag: 'tag',
  link: 'link',
  'box-arrow-up-right': 'external-link',
  'arrow-up-right': 'external-link',
  eye: 'eye',
  'eye-slash': 'eye-off',
  play: 'play',
  pause: 'pause',
  clock: 'clock',
  'arrow-clockwise': 'refresh-cw',
  'box-arrow-right': 'log-out',
  'credit-card': 'credit-card',
  list: 'list',
  sun: 'sun',
  moon: 'moon',
  circle: 'circle',
  loader: 'loader-circle',
  'list-ul': 'list',
  'journal-code': 'file-code',
  'journal-text': 'file-text',
  'diagram-3': 'network',
  'shield-check': 'shield-check',
  'shield-lock': 'shield',
  'box-arrow-in-right': 'log-in',
  'person-plus': 'user-plus',
  'person-gear': 'user-cog',
  'gear-wide-connected': 'settings',
  'cloud-upload': 'cloud-upload',
  'cloud-download': 'cloud-download',
  'arrow-repeat': 'refresh-cw',
  'plus-circle': 'circle-plus',
  'dash-circle': 'circle-minus',
  'x-lg': 'x',
  'check-lg': 'check',
  'chevron-bar-left': 'chevrons-left',
  'chevron-bar-right': 'chevrons-right',
  'skip-backward': 'skip-back',
  'skip-forward': 'skip-forward',
  'fast-forward': 'fast-forward',
  'rewind': 'rewind',
  'activity': 'activity',
  'bar-chart': 'chart-bar',
  'pie-chart': 'chart-pie',
  'graph-up': 'trending-up',
  'cpu': 'cpu',
  'hdd': 'hard-drive',
  'wifi': 'wifi',
  'plug': 'plug',
  'tools': 'wrench',
  'wrench': 'wrench',
  'hammer': 'hammer',
  'bug': 'bug',
  'lightning': 'zap',
  'stars': 'sparkles',
  'robot': 'bot',
  'chat': 'message-circle',
  'chat-dots': 'message-circle',
  'send': 'send',
  'inbox': 'inbox',
  'bell': 'bell',
  'bell-slash': 'bell-off',
  'calendar': 'calendar',
  'calendar-event': 'calendar',
  'clock-history': 'history',
  'hourglass': 'hourglass',
  'stopwatch': 'timer',
  'flag': 'flag',
  'bookmark': 'bookmark',
  'heart': 'heart',
  'hand-thumbs-up': 'thumbs-up',
  'hand-thumbs-down': 'thumbs-down',
  'exclamation-diamond': 'diamond',
  'shield-exclamation': 'shield-alert',
  'file-earmark': 'file',
  'file-earmark-code': 'file-code',
  'file-earmark-text': 'file-text',
  'folder2-open': 'folder-open',
  'collection': 'layers',
  'grid': 'layout-grid',
  'layout-sidebar': 'panel-left',
  'layout-text-window': 'panel-top',
  'window': 'app-window',
  'display': 'monitor',
  'phone': 'smartphone',
  'tablet': 'tablet',
  'laptop': 'laptop',
  'printer': 'printer',
  'camera': 'camera',
  'image': 'image',
  'images': 'images',
  'palette': 'palette',
  'brush': 'brush',
  'paint-bucket': 'paint-bucket',
  'droplet': 'droplet',
  'funnel': 'filter',
  'sort-down': 'arrow-down',
  'sort-up': 'arrow-up',
  'arrow-down-up': 'arrow-up-down',
  'arrows-expand': 'maximize',
  'arrows-collapse': 'minimize',
  'fullscreen': 'maximize',
  'fullscreen-exit': 'minimize',
  'zoom-in': 'zoom-in',
  'zoom-out': 'zoom-out',
  'pin': 'pin',
  'pin-map': 'map-pin',
  'geo-alt': 'map-pin',
  'map': 'map',
  'compass': 'compass',
  'signpost': 'signpost',
  'signpost-2': 'signpost',
  'door-open': 'door-open',
  'door-closed': 'door-closed',
  'house-door': 'door-open',
  'building': 'building',
  'buildings': 'building-2',
  'bank': 'landmark',
  'cash': 'banknote',
  'currency-dollar': 'dollar-sign',
  'currency-euro': 'euro',
  'currency-pound': 'pound-sterling',
  'wallet': 'wallet',
  'wallet2': 'wallet',
  'receipt': 'receipt',
  'cart': 'shopping-cart',
  'bag': 'shopping-bag',
  'basket': 'shopping-basket',
  'gift': 'gift',
  'trophy': 'trophy',
  'award': 'award',
  'patch-check': 'badge-check',
  'patch-exclamation': 'badge-alert',
  'patch-question': 'badge-question-mark',
  'patch-plus': 'badge-plus',
  'patch-minus': 'badge-minus',
  'slash-circle': 'circle-slash',
  'ban': 'ban',
  'power': 'power',
  'toggle-on': 'toggle-right',
  'toggle-off': 'toggle-left',
  'sliders': 'sliders-horizontal',
  'sliders2': 'sliders-horizontal',
  'toggles': 'toggle-left',
  'toggles2': 'toggle-right',
  'ui-checks': 'list-checks',
  'ui-radios': 'circle-dot',
  'input-cursor': 'text-cursor',
  'textarea-t': 'text',
  'type': 'type',
  'fonts': 'type',
  'translate': 'languages',
  'globe2': 'globe',
  'link-45deg': 'link',
  'link-break': 'unlink',
  'paperclip': 'paperclip',
  'scissors': 'scissors',
  'eraser': 'eraser',
  'rulers': 'ruler',
  'ruler': 'ruler',
  'bounding-box': 'square',
  'aspect-ratio': 'ratio',
  'columns': 'columns-2',
  'columns-gap': 'columns-3',
  'layout-three-columns': 'columns-3',
  'layout-split': 'split',
  'layout-wtf': 'layout-template',
  'kanban': 'kanban',
  'table': 'table',
  'list-nested': 'list-tree',
  'tree': 'list-tree',
  'diagram-2': 'git-branch',
  'git': 'git-branch',
  '-bezier': 'git-branch',
  '-bezier2': 'git-merge',
  'node-plus': 'git-branch-plus',
  'share': 'share-2',
  'reply': 'reply',
  'reply-all': 'reply-all',
  'forward': 'forward',
  'megaphone': 'megaphone',
  'broadcast': 'radio',
  'rss': 'rss',
  'newspaper': 'newspaper',
  'book': 'book',
  'journal': 'book-open',
  'journal-bookmark': 'book-marked',
  'mortarboard': 'graduation-cap',
  'easel': 'presentation',
  'easel2': 'presentation',
  'easel3': 'presentation',
  'puzzle': 'puzzle',
  'puzzle-fill': 'puzzle',
  'plugin': 'plug',
  'extension': 'puzzle',
  'braces': 'braces',
  'braces-asterisk': 'braces',
  'code-slash': 'code',
  'code-square': 'square-code',
  'terminal-fill': 'terminal',
  'console': 'terminal',
  'window-desktop': 'monitor',
  'window-dock': 'panel-bottom',
  'window-sidebar': 'panel-left',
  'app': 'app-window',
  'app-indicator': 'app-window',
  'boxes': 'boxes',
  'box-seam': 'package',
  'inboxes': 'inbox',
  'archive': 'archive',
  'archive-fill': 'archive',
  'trash3': 'trash-2',
  'recycle': 'recycle',
  'arrow-counterclockwise': 'rotate-ccw',
  'arrow-clockwise-fill': 'refresh-cw',
  'symmetry-horizontal': 'flip-horizontal',
  'symmetry-vertical': 'flip-vertical',
  'shuffle': 'shuffle',
  'repeat': 'repeat',
  'repeat-1': 'repeat-1',
  'volume-up': 'volume-2',
  'volume-down': 'volume-1',
  'volume-mute': 'volume-x',
  'volume-off': 'volume-off',
  'mic': 'mic',
  'mic-mute': 'mic-off',
  'headphones': 'headphones',
  'speaker': 'speaker',
  'music-note': 'music',
  'music-note-beamed': 'music-2',
  'film': 'film',
  'camera-video': 'video',
  'camera-video-off': 'video-off',
  'webcam': 'webcam',
  'broadcast-pin': 'radio',
  'cast': 'cast',
  'airplay': 'airplay',
  'disc': 'disc',
  'vinyl': 'disc-2',
  'optical-audio': 'audio-lines',
  'soundwave': 'audio-waveform',
  'badge-ad': 'badge',
  'badge-cc': 'badge',
  'badge-hd': 'badge',
  'badge-sd': 'badge',
  'badge-tm': 'badge',
  'badge-vo': 'badge',
  'badge-vr': 'badge',
  'badge-wc': 'badge',
  'badge-ar': 'badge',
  'badge-8k': 'badge',
  'badge-4k': 'badge',
  'badge-3d': 'badge',
};

function toPascalCase(name: string): string {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function resolveIconName(name: string): string {
  return ICON_NAME_MAP[name] ?? name;
}

@customElement('sl-icon')
export class SlIcon extends UiElement {
  @property({ type: String }) name = '';
  @property({ type: String }) src = '';
  @property({ type: String }) library = 'default';
  @property({ type: String }) slot = '';
  @property({ type: String }) label = '';

  render() {
    if (this.src) {
      return html`<img
        part="svg"
        src=${this.src}
        alt=""
        class="inline-block h-4 w-4 shrink-0"
        aria-hidden="true"
      />`;
    }

    const lucideName = resolveIconName(this.name);
    const pascalName = toPascalCase(lucideName);
    const iconDef = (icons as Record<string, IconNode>)[pascalName];
    if (!iconDef) {
      return html`<span
        part="svg"
        class="inline-block h-4 w-4"
        aria-hidden="true"
      ></span>`;
    }
    const svg = createElement(iconDef, {
      width: 16,
      height: 16,
      'stroke-width': 2,
      class: 'shrink-0',
    });
    return html`<span
      part="svg"
      class="inline-flex items-center justify-center"
      aria-hidden=${this.label ? 'false' : 'true'}
      aria-label=${this.label || ''}
      >${svg}</span
    >`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'sl-icon': SlIcon;
  }
}
