apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spacebridge.fullname" . }}
  labels:
    {{- include "spacebridge.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.environment.jwtSecret | b64enc | quote }}
  {{- if .Values.config.openai.apiKey }}
  openai-api-key: {{ .Values.config.openai.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.anthropic.apiKey }}
  anthropic-api-key: {{ .Values.config.anthropic.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.sentry.enabled }}
  sentry-dsn: {{ .Values.sentry.dsn | b64enc | quote }}
  {{- end }}
