{{- if .Values.preloop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "preloop_ai.fullname" . }}-spacelit-preloop
  labels:
    {{- include "preloop_ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: spacelit-preloop
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "preloop_ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: spacelit-preloop
{{- end }}
