{{- if .Values.preloop.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "preloop_ai.fullname" . }}-spacelit-preloop
  labels:
    {{- include "preloop_ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: spacelit-preloop
    app: spacelit-preloop
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "preloop_ai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: spacelit-preloop
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "preloop_ai.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: spacelit-preloop
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "preloop_ai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: spacelit-preloop
          image: "{{ .Values.preloop.repository }}:{{ .Values.preloop.tag }}"
          imagePullPolicy: {{ .Values.preloop.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/templates
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "preloop_ai.fullname" . }}-nginx
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
