apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spacebridge.fullname" . }}-spacelit
  labels:
    {{- include "spacebridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: spacelit
    app: spacelit
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spacebridge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: spacelit
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spacebridge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: spacelit
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spacebridge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: spacelit
          image: "{{ .Values.spacelit.repository }}:{{ .Values.spacelit.tag }}"
          imagePullPolicy: {{ .Values.spacelit.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/templates
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "spacebridge.fullname" . }}-nginx
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
